### ISSUE TITLE
HTTP Error 403 while downloading resnest101 pretrained model 

### ISSUE THREAD

**Issue by essalim** [zhanghang1989/ResNeSt#153]
Hello, while this used to work fine a couple of days ago, now it is giving HTTP Eroor 403: Forbidden.

from resnest.torch import resnest101
self.model = resnest101(pretrained=True)

any idea what could be the issue?

**Comment by zhanghang1989** [comment]
Hi, sorry about that. Wasabi cloud has a rule of limited downloading volume. I am looking for other solutions

**Comment by zhanghang1989** [comment]
Hi @essalim , could you download the model weights from https://dl.dropboxusercontent.com/s/x5qr07zpl9pxufw/resnest101-22405ba7.pth?dl=0

**Comment by essalim** [comment]
thank you @zhanghang1989 I used your link for downlaod :)

**Comment by cenkbircanoglu** [comment]
Hi, I wanted to do some experiments by using all versions of resnest. Can you share the other checkpoints also, please?

**Comment by zs-zhong** [comment]
Hi @zhanghang1989, same request. I also want to do some experiments by using resnest-200 and 269. Can you please share the related checkpoints? Thx!

**Comment by zhanghang1989** [comment]
Here are the links :
https://drive.google.com/file/d/1uSSvy4V7ALjousc7Tqy3tlGH7nLUijhG/view?usp=sharing
https://drive.google.com/file/d/1dwMhRiuz-E7je-gK0mEFrIXp33MU2_FP/view?usp=sharing

**Comment by ds2268** [comment]
@zhanghang1989 can you also provide links to pre-trained resnest-50 model?

**Comment by harveenchadha** [comment]
Can you please provide the link for resnest50 as well?

**Comment by zhanghang1989** [comment]
> Can you please provide the link for resnest50 as well?

The model access has been fixed. Try following the README to get pretrained models.

**Comment by JagadishSivakumar** [comment]
timm pretrained resnest weights @harveenchadha 

https://www.kaggle.com/ar90ngas/timm-pretrained-resnest

**Comment by zhanghang1989** [comment]
The model access has been fixed. Could you reinstall the newest version of the code?

**Comment by brendanwallison** [comment]
This is still an issue, even with the newest version of the code.

**Comment by atamazian** [comment]
I'm also getting 403 error.

**Comment by zhanghang1989** [comment]
Did you reinstall the library?
